version: '3'
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "8282:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  # This is our static website with a bootstrap template and making ajax
  # jqueries to our dynamic server
  ajax:
    build: ../Step4-AjaxJQery/docker-images/ajax-query/.
    image: api/ajax
    # Will launch 2 instances of this image
    deploy:
      replicas: 2
    labels:
    # Theses containers will be accessible from localhost:8282/ with stick
    # session enabled
     - "traefik.enable=true"
     - "traefik.http.routers.ajax.rule=PathPrefix(`/`)"
     - "traefik.http.services.ajax.loadbalancer.sticky=true"
     - "traefik.http.services.ajax.loadbalancer.sticky.cookie.name=StickyCookie"


  # This is our dynamic server delivering a JSON table containing random
  # content (names and animals species with birthdates, etc) on port 3000
  # every time a request is made
  express:
    build: ../Step2-Dynamic-HTTP/docker-images/express-image/.
    image: api/express
    # Will launch 2 instances of this image
    deploy:
      replicas: 2
    labels:
    # Theses containers will be accessible from localhost:8282/api/animals/
    # and Traefik will redirect the requests to the port 3000 and replace
    # "/api/animals/" by "/"
      - "traefik.enable=true"
      - "traefik.http.services.express.loadbalancer.server.port=3000"
      - "traefik.http.routers.express.rule=PathPrefix(`/api/animals/`)"
      - "traefik.http.routers.express.middlewares=express-replacepath"
      - "traefik.http.middlewares.express-replacepath.replacepath.path=/"

  portainer:
    # Portainer management UI
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
